# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.serverlist = QtWidgets.QListWidget(self.centralwidget)
        self.serverlist.setObjectName("serverlist")
        self.horizontalLayout_2.addWidget(self.serverlist)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 4, 1, 3)
        self.openfolder_button = QtWidgets.QPushButton(self.centralwidget)
        self.openfolder_button.setObjectName("openfolder_button")
        self.gridLayout.addWidget(self.openfolder_button, 0, 3, 1, 1)
        self.change_button = QtWidgets.QPushButton(self.centralwidget)
        self.change_button.setObjectName("change_button")
        self.gridLayout.addWidget(self.change_button, 0, 5, 1, 1)
        self.option_button = QtWidgets.QPushButton(self.centralwidget)
        self.option_button.setObjectName("option_button")
        self.gridLayout.addWidget(self.option_button, 0, 1, 1, 1)
        self.about_button = QtWidgets.QPushButton(self.centralwidget)
        self.about_button.setObjectName("about_button")
        self.gridLayout.addWidget(self.about_button, 0, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.gridLayout.addWidget(self.save_button, 0, 2, 1, 1)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setObjectName("next_button")
        self.gridLayout.addWidget(self.next_button, 0, 6, 1, 1)
        self.ftpbutton = QtWidgets.QPushButton(self.centralwidget)
        self.ftpbutton.setObjectName("ftpbutton")
        self.gridLayout.addWidget(self.ftpbutton, 0, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.locallist = QtWidgets.QListWidget(self.centralwidget)
        self.locallist.setObjectName("locallist")
        self.horizontalLayout.addWidget(self.locallist)
        self.reloadbutton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadbutton.setObjectName("reloadbutton")
        self.horizontalLayout.addWidget(self.reloadbutton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openfolder_button.setText(_translate("MainWindow", "open folder"))
        self.change_button.setText(_translate("MainWindow", "changedir"))
        self.option_button.setText(_translate("MainWindow", "Options"))
        self.about_button.setText(_translate("MainWindow", "About"))
        self.save_button.setText(_translate("MainWindow", "savefile"))
        self.next_button.setText(_translate("MainWindow", "nextdir"))
        self.ftpbutton.setText(_translate("MainWindow", "ftp-connect"))
        self.reloadbutton.setText(_translate("MainWindow", "reload"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
